name: flutter_widgets
version: 0.1.7+1
description: >
  Flutter widgets that are developed by Google but not by the core
  Flutter team.
homepage: https://github.com/google/flutter.widgets

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  flutter: ^1.9.1

dependencies:
  collection: any
  flutter:
    sdk: flutter
  html: any
  meta: any
  quiver: any

dev_dependencies:
  test: any
  mockito: any
  pedantic: any
  flutter_test:
    sdk: flutter
